version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment:
    build:
      context: ./services/payment
    container_name: payment-service
    ports:
      - "3002:3002"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3002"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  parking:
    build:
      context: ./services/parking
    container_name: parking-service
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-tests:
    build:
      context: ./services/payment
    container_name: payment-tests
    environment:
      API_HOST: payment
    depends_on:
      payment:
        condition: service_healthy
    command: ["npm", "test"]

  parking-tests:
    build:
      context: ./services/parking
    container_name: parking-tests
    environment:
      API_HOST: parking
    depends_on:
      parking:
        condition: service_healthy
    command: ["npm", "test"]

volumes:
  rabbitmq_data:
